# Generated by Django 2.2.3 on 2019-08-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190815_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='Ingredient Sub State', max_length=256)),
            ],
            options={
                'db_table': 'substate',
            },
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Ingredient Sub Type', max_length=256)),
            ],
            options={
                'db_table': 'subtype',
            },
        ),
    ]
