# Generated by Django 2.2.3 on 2019-08-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_substate_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitingredient',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='items.SubState'),
        ),
        migrations.AddField(
            model_name='unitingredient',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='items.SubType'),
        ),
        migrations.AlterField(
            model_name='unitingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unitingredient',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='items.Unit'),
        ),
    ]
