# Generated by Django 2.2.3 on 2019-08-18 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20190818_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitingredient',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.SubSize'),
        ),
        migrations.AlterField(
            model_name='unitingredient',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.SubState'),
        ),
        migrations.AlterField(
            model_name='unitingredient',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.SubType'),
        ),
    ]
